apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: evs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: evs.csi.cloud.ru
allowVolumeExpansion: true
parameters:
  type: SSD
reclaimPolicy: Delete
